version: '3.7'

services:
    app_she:
        build: .
        restart: unless-stopped
        container_name: app_she
        ports:
            - "811:80" # HTTP
            - "8453:443" # HTTPS
        volumes:
            - .:/app
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - backend
volumes:
    caddy_data:
    caddy_config:
networks:
    backend:
        driver: bridge


